name: frontend
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.6.1
  flutter_svg: ^1.1.0
  cupertino_icons: ^1.0.8
  provider: ^6.0.0
  http: ^1.2.2
  flutter_secure_storage: ^5.0.0
  image_picker: ^1.1.2
  mime: ^1.0.0
  shared_preferences: ^2.0.14
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  assets:
    - assets/images/profile_pic.jpg
    - assets/icons/NU_shield.svg
    - assets/images/NUCCIT_Logo.png
  uses-material-design: true
